[cols="1,5"]
|===
| *Latest ILT slides*
| image:https://img.shields.io/badge/ILT_Slides-latest-blue[ILT Slides, link=https://cockroachlabs.github.io/cockroach-university-ilt-operational-fundamentals, window=_blank]
|===

= Presentation Slides
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:toc:
:toclevels: 5
:toc-placement!:

This repository contains slides used to lead instructor-led training. Check out the various sections to see how to contribute and how to build.

toc::[]

== Prerequisite installations

* If you're on a Mac using Homebrew: `brew install node`

== Quickstart

. Clone the repo, or git pull if you already have it cloned
. Run `npm install`
. Run `npm start`
. *Click the link* in the terminal to view the slides at `http://localhost:8000`

NOTE: This is ONLY needed if you wish to make changes to the content and _see the results automatically in the browser_.

The slides are a static asset that can be generated by instead running the following commands:

. Run `npm install`
. Run `npm run clean && npm run build`

You can either check out the generated assets in the `build` folder, or if you wish to take them elsewhere, perform the following additional steps:

[start=3]
. Run `npm run package`
. Grab the ZIP file in the root directory, drop it on any target machine, and unzip it.
. From there, you can navigate to the `index.html` file.

To clean out a previous round of generated assets, run `npm run clean`.

NOTE: The `index.html` file that is generated along with other generated artifacts are excluded from git.

== Key Concepts

=== Format

This content is built using *Reveal.js*.
Reveal.js is a source-code friendly way to assemble slides.
Instead of heavy-handed slide tools like PowerPoint, Keynote, or Google Slides, this is a text-based collection of slides with a more dynamic nature.
This is source-code friendly and easy to resolve conflicts.

Reveal.js has a unique structure compared to traditional slide tools.
A traditional deck has a single path through its content often seen as a vertical.
Reveal.js allows us to stack a sequence of verticals along a horizontal line, giving it a "2-D" nature.
This means you can move down through a given vertical to go through its particular content.
When completed, you can then "move right" to then tackle the next topic (perhaps after taking a break!)

At any time you are going through a Reveal.js deck, you can hit ESC or "o" to enter *Overview* mode, and see at a glance the 2-D matrix of slides.

We are also using *Asciidoctor* as the mechanism to craft the Reveal.js content.
Asciidoctor is very sophisticated compared to Markdown, a common tool used to write content.
This means that just about anything possible with Asciidoctor is possible with these slides.

We also have some customized CSS styling to tailor the content for our own needs.

=== Structure

The source content is created in the following folder structure:

```
/images
    /day-01
        /chapter-01
            24-7-up.svg
            ...
        /chapter-02
        ...
    /day-02
        ...
    /day-03
        ...
/slides
    /day-01
        /chapter-01
            chapter-01.adoc  // aggregates the rest of adoc files in this folder
            00-course-intro-agenda.adoc
            01-intro-to-crdb.adoc
            ...
        /chapter-02
        /chapter-03
        chapter-01-course.adoc
        chapter-02-course.adoc
        ...
    /day-02
        ...
    /day-03
        ...
```

This is where the content lives and has a consistent structure.

=== Speaker Notes

This content also has additional *speaker notes* for additional content.

There are two possible versions of speaker notes, *instructor-based* (default) and *student-based*. A separate version of the slides are generated for each.

If you want to see the speaker notes while walking through any course, simply hit "s".

== Exporting a course into a PDF

There are two ways to generate PDFs from the course content:

=== Automated PDF Generation

You can use the gulp task to automatically generate PDFs for the course:

```bash
# Generate complete course PDFs (instructor and student versions)
gulp build-instructor-pdf

# Generate PDFs for a specific day
gulp build-instructor-pdf --day 01

# Generate PDFs for a specific chapter
gulp build-instructor-pdf --day 01 --chapter 01
```

The PDFs will be generated in the `build/pdf` directory, maintaining the same structure as the HTML files.

=== Manual PDF Generation

If you wish to manually export a PDF version of a given course, do the following:

. Generate the files using `npm run build`.
. Visit the `build` folder and open the `index.html` file.
. Navigate to the day's content you wish to export.
. In your browser's URL bar, append `?print-pdf&showNotes=separate-page`. This will render the HTML in a PDF-friendly format with the speaker notes on separate page.
. Hit CMD-P (or CTRL-P on Windows/Linux) to open up the Print Dialog.
. Choose "Save as PDF"
. Pick your folder to put the PDF file.

== Making Contributions

=== Creating a slide

A single Asciidoctor file can contain multiple slides.

* Title slides are prefixed with a Document Title section title:

----
= Major Course (title slide)
----

* The opening slide for a major section is prefixed with a Level 1 section title:

----
== Main slide of this section
----

* Sub-slides for that section, rendered vertically by reveal.js, are prefixed with a Level 2 section title:

----
=== Sub-slide found "below" the main slide
----

This title defines the beginning of a slide. Below that, place your content. The most common thing is a list of bullet points:

----
* Point A
* Point B
* Point C
----

If you wish to have your bullet points revealed one-by-one by pressing the down key:

----
[%step]
* Point A
* Point B
* Point C
----

NOTE: See https://docs.asciidoctor.org/reveal.js-converter/latest/converter/syntax/fragment/#step-option[this for more details on steps].

For more details about layout including multi-columned content, checkout https://docs.asciidoctor.org/reveal.js-converter/latest/converter/syntax/layout/[Asciidoctor reveal.js].

==== Putting in the key image and corresponding bullet points.

. Put any new images into the `images/day-n/chapter-m/` folder (plugging in the appropriate _day_ and _chapter_)
. In the Asciidoctor file, introduce the following:
+
----
image::images/day-01/chapter-01/24-7-up.svg[]
----
+
. Put in your bullet points.
+
----
* Point A
* Point B
* Point C
----
+
. Apply any <<speaker-notes, speaker notes>>.

[[columns]]
==== Changing a slide to a column-based layout

NOTE: See https://docs.asciidoctor.org/reveal.js-converter/latest/converter/syntax/layout/#columns-layout[here for more options].

Occasionally, you'll want to switch from the top-down style and instead have a column-based one for a given slide.
Considering this is a slide show, the odds of having more than two columns is quite slim, so it's actually quite easy to make this.

[subs="quotes"]
----
*[.columns]*
=== Modern system data

*[.column]*
image::images/day-01/chapter-01/database_2.svg[]

*[.column]*
* Point A
* Point B
* Point C
----
* Add the *[.columns]* role to the slide header.
* For each piece of content, add the *[.column]* role.

By default, this will divide the space equally between both parts.
However, you can adjust one of the columns proportionally, and the other will follow.

[subs="quotes"]
----
*[.column.is-one-quarter]*
image::images/day-01/chapter-01/database_2.svg[]

[.column]
* Point A
* Point B
* Point C
----
* By using *[.column.is-one-quarter]*, you are actually applying two Reveal.js classes, *.column* and *.is-one-quarter*.
This will shrink the first column from 1/2 to 1/4, and the second column will expand to 3/4.
* You can use any of the following:
** *is-three-quarters*
** *is-two-thirds*
** *is-half*
** *is-one-third*
** *is-one-quarter*
** *is-full*
* To repeat the point, with only two columns, the modifier only needs to be added to one column. The other will adjust automatically.

A common issue when using column-based layouts is that one column will be taller than the other.
If you want to vertically center the columns, then apply this additional setting:

[subs="quotes"]
----
*[.columns.is-vcentered]*
=== Modern system data

[.column]
image::images/day-01/chapter-01/database_2.svg[]

[.column]
* Point A
* Point B
* Point C
----
* By applying *[.columns.is-vcentered]*, you are asking Reveal.js to vertically center columns.

==== Creating a slide with no title text

Sometimes, you need to create a slide with a single image, or perhaps a simple piece of text.
To do that, you still need to create the Level 2 or Level 3 header, but instead of putting in a title, you instead put in `!`.
See below:

.Level 2 example
----
== !

This top-level slide has no title, but will only show this text block
----

.Level 3 example
----
=== !

This vertical sub-slide has no title either, but will show only this content

[.notes]
--
You can still include speaker notes as well!
--
----

NOTE: You can NOT do this on title slides! Title slides will simply render a giant "!" if you attempt it.

=== Speaker Notes

This section shows how to add additional content to slides known as *speaker notes*.

* When viewing a deck inside a browser, hit "s" on any given slide to bring up a separate window.
** Feel free to put this separate window on your local screen and NOT on the presenting screen.
** This will show the speaker notes.
** It will also show the current slide along with multiple timers.

==== Adding speaker notes to a slide.

To add speaker notes to any given slide, add the *[.notes]* fragment as shown below:

[subs="quotes"]
----
=== My cool slide

*[.notes]
--
My speaker notes
--*
----
* The speaker notes should be placed below all the content _for that slide_.
* The content inside the speaker notes tags can be styled the same as any other
* These notes will be included in *_all_* version of the slides.

==== Student-only speaker notes

We have a special attribute, `student`, that when switched to `true` can be used to create student-only content, as shown below:

[subs="quotes"]
----
[.notes]
--
*ifdef::student[]*
Student speaker notes
*endif::[]*
--
----
* This example only shows speaker notes, but it's important to remember that any speaker notes should be placed after that slide's content.
* Notice the bolded *ifdef::student[]* and *endif::[]* tags. Both of these tags must be in place.
* These notes will *_only_* be included in the `student-*.html` versions of the slides.

==== Instructor-only speaker notes

If you wish to have speaker notes that are instructor-only, apply the following:

[subs="quotes"]
----
[.notes]
--
*ifndef::student[]*
Instructor speaker notes
*endif::[]*
--
----
* It's important to observe that `ifndef` means "if not defined", and uses the same `student` attribute mentioned earlier.
* These notes will *_only_* be included in the non- `student-*.html` versions of the slides.
* Again, such speaker notes must be placed _after_ the slide's content.

==== Student-only and instructor-only speaker notes

Finally, what if you need both student-only AND instructor-only speaker notes?

[subs="quotes"]
----
[.notes]
--
*ifdef::student[]*
Student speaker notes
*endif::[]*
*ifndef::student[]*
Instructor speaker notes
*endif::[]*
--
----
* Simply copying the fragments from the earlier student-only and instructor-only sections and putting *both* into the speaker note tags will generate two different sets of speaker notes.
* Again, put any speaker notes _below_ the slide's content.

=== Adding a new chapter

If you are adding a new chapter (imagine it's chapter 4), do the following:

. Create a new folder `slides/chapter-04/`.
. Create `slides/chapter-04/chapter-04.adoc` as an aggregator for your sections.
. Inside `slides/chapter-04/` start making AsciiDoc files for each section, e.g. `01-why-i-like-crdb.adoc`.
. Inside `slides/chapter-04/chapter-04.adoc` use `include` directives to pull in each AsciiDoc file you created. (See link:slides/chapter-01/chapter-01.adoc[] as an example).

IMPORTANT: Do NOT apply any formatting in this aggregator!

If you are simply adding a new section to an existing chapter, then you may forgo steps 1 and 2 and simply update the aggregator with an include to your new section.

From there, you must decide what top level courses need to include Chapter 4.
The ones that need it, you add an `include::slides/chapter-04/chapter-04.adoc[]` directive.

=== Examples

Below are various examples of slides.

==== A top slide followed by a vertical sub-slide

The following AsciiDoc fragment shows two slides with some speaker notes.

----
== Problems CockroachDB Solves

[.notes]
--
In this section, we're going to highlight the problems CRDB solves. We'll first highlight the problems or challenges modern systems face.
--

=== Modern system data

image::images/day-01/chapter-01/database_2.svg[]

* There are many different types of data in modern systems:
** analytical vs transactional
** incidental to business critical
** eventually consistent vs strongly consistent
** unstructured to highly structured
** relational model vs document model
* What type is CockroachDB designed for?
----
* The "Problems" slide with `==` (Level 1 section) denotes a top slide. Top slides navigate horizontally.
* The "Modern" slide with `===` (Level 2 section) denotes a sub-slide. Sub-slides navigate vertically.
* The first slide has speaker notes denoted by the `[.notes]` role and the double-dash block.
* Compared to Markdown, there is no need for break to signal where a slide ends.
* Whereas in Markdown there was text like "Image placeholder" which is an images "alt text", there is no need for it.
* In AsciiDoc, unordered lists are created using `\*` (asterisk) deeper indentations are created with `**` (double asterisk). Deeper levels are created by increasing number of asterisks.

==== A slide with 2 columns

The following AsciiDoc fragment shows a slide with an image and some bullet points, but laid out horizontally.

[subs="quotes"]
----
*[.columns.is-vcentered]*
=== Modern system data

*[.column.is-two-thirds]*
image::images/day-01/chapter-01/database_2.svg[]

*[.column]*
* Point A
* Point B
* Point C
----
* The `.columns` role (note the plural usage of *columns*) applied to the slide's title will make this slide use a column-based structure.
* The additional `.is-vcenter` role, stacked onto the `.columns` role, signals that this slide will center things vertically, which is often what's needed for a column-based slide.
* The `.column` role (note the singular usage of *column*) applied to each block signals where the columns are. By default, columns are split equally.
* The `.is-two-thirds` role, stacked onto the `.column` role, signals that this column should instead be given 2/3 of the space, causing the 2nd column to only get 1/3.

IMPORTANT: You do NOT have to use `.is-vcentered` or `.is-two-thirds`. These are options to tweak the layout.

It's also important to understand that you can actually have as many columns as you like.
However, for a slide-based presentation where the real estate is limited, the instances of having 3+ columns will be rare.

NOTE: See <<columns, Changing a slide to a column-based layout>> for more details and options.

==== A slide with custom-sized text

Asciidoctor by default renders a slide's title text into an `<h2>` element.
This results in the same size for title text, whether it's a top-level horizontal slide or a vertical sub-slide.
We have customized CSS that automatically styles every vertical sub-slide with `<h3>` type sizing.

If you want to further adjust the sizing of either a slide's title text or any other block of text, check out the following instructions:

. To alter the sizing of a slide's title text, move the title text down into the slide and make it into a <<Creating a slide with no title text, slide with no title>>.
. Apply one of the following styles to the text block.
** `[.h2-style]`
** `[.h3-style]`
** `[.h4-style]`

For example:

[subs="quotes"]
----
=== !

*[.h4-style]*
Cloud 2.0: Introduces Standard plan

The Standard plan offers managed clusters with full operational features and provisioned capacity, positioned between the Basic (formerly Serverless) and Advanced (formerly Dedicated) plans.
----
* This slide will be rendered with no title.
* The first text block will be rendered with Reveal.js's Level 4 sizing.
* the second text block will be rendered with standard sizing.

The following example uses the same technique to render a slide with what looks like two headers:

[literal]
----
=== !

[.h4-style]
There are two ways to consume CockroachDB

[.h3-style]
Self-Hosted and Cloud
----
* The slide has no title due to `=== !`.
* The first block of text has `[.h4-style]`, which will apply Reveal.js's level 4 styling.
* The second block of text has `[.h3-style]`, which will apply Reveal.js's level 3 styling.

It's also possible to apply this styling to other blocks.
[literal]
----
=== Yet Another Example

[.h4-style]
* You can also
* Apply it to
* Lists
----

[WARNING]
====
Do NOT apply these styles to the top of a slide like this:

[subs="quotes"]
----
*[.h4-style]*      <--- don't do this!
=== Another slide
----

If you do this, the formatting will be wrong.
These custom roles are designed to make other blocks *look* like header-styled elements.
====

==== A multi-grid layout

If you need a slide to have grid layout, in general you'll need to render a table.
As an example, imagine two columns where each column has a graphic above.
This is best rendered using a 2x2 table as shown below:

[literal]
----
[cols="^1a,^1a", frame=none, grid=none]
|===
| image::images/day-01/chapter-99/increased.svg[]
| image::images/day-01/chapter-99/decreased.svg[]

| * Increased transaction throughput
| * Reduced tail latency for better performance
|===
----
* The `|===` directive signals the top and bottom of a table.
* The `[cols]` header defines the structure of the table.
** Because there are two numbers separated by a comma, this is a 2-column table.
** The `^` (caret) symbol signifies a column that is horizontally centered.
** The numbers indicate how much weight is given to the column. In this case, each has `1`, hence both are equal.
** The `a` next to the numbers indicate that this column will apply Asciidoctor formatting.
** The `frame=none` attribute signals that no frame is to be drawn around the exterior of the table.
** The `grid=none` attribute signals that no lines are to be drawn between the cells.
* The `|` directive denotes a cell, and as you read top-to-bottom, the cells go left-to-right.
* The line break signals a new row. While we have the `cols` directive signaling how many columns to draw and don't have to do this, it's common convention to do it anyway for better readability.

NOTE: See https://docs.asciidoctor.org/asciidoc/latest/tables/build-a-basic-table/[Build a Basic Table for more details.]
